create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  birth_date date not null,
  zodiac_name text not null,
  zodiac_trait text,
  main_numbers int[] not null,
  bonus_number int not null,
  explanation text
);

create index if not exists lotto_draws_created_at_idx on public.lotto_draws (created_at desc);
create index if not exists lotto_draws_birth_date_idx on public.lotto_draws (birth_date);
create index if not exists lotto_draws_zodiac_name_idx on public.lotto_draws (zodiac_name);
